---------                                           SQL PROJECT - EV Charging Station Utilization

--1. Total Revenue Generated by Each Station

SELECT cs.station_id, cs.station_name, SUM(s.amount_paid) AS total_revenue
FROM charging_sessions s
JOIN charging_stations cs ON s.station_id = cs.station_id
GROUP BY cs.station_id, cs.station_name
ORDER BY total_revenue DESC;

--2. Average Charging Time per Session

SELECT ROUND(AVG(TIMESTAMPDIFF(MINUTE, start_time, end_time)), 2) AS avg_session_minutes
FROM charging_sessions;

--3. Top 5 Most Utilized Stations (by Session Count)

SELECT cs.station_name, COUNT(*) AS session_count
FROM charging_sessions s
JOIN charging_stations cs ON s.station_id = cs.station_id
GROUP BY cs.station_name
ORDER BY session_count DESC
LIMIT 5;

--4. Peak Charging Hours of the Day

SELECT HOUR(start_time) AS hour, COUNT(*) AS total_sessions
FROM charging_sessions
GROUP BY hour
ORDER BY total_sessions DESC;

--5. Monthly Revenue Trend

SELECT MONTH(start_time) AS month, SUM(amount_paid) AS monthly_revenue
FROM charging_sessions
GROUP BY month
ORDER BY month;

--6. Repeat Users – More Than 3 Charging Sessions

SELECT user_id, COUNT(*) AS session_count
FROM charging_sessions
GROUP BY user_id
HAVING session_count > 3;

--7. Most Common Vehicle Models Charged

SELECT v.vehicle_model, COUNT(*) AS count
FROM charging_sessions s
JOIN vehicles v ON s.vehicle_id = v.vehicle_id
GROUP BY v.vehicle_model
ORDER BY count DESC;

--8. Average Energy (kWh) Consumed per Vehicle Type

SELECT u.vehicle_type, ROUND(AVG(s.energy_kwh), 2) AS avg_energy_kwh
FROM charging_sessions s
JOIN users u ON s.user_id = u.user_id
GROUP BY u.vehicle_type;

--9. Failed Transactions Report

SELECT *
FROM payments
WHERE payment_status = 'Failed';

--10. Top Cities by Charging Activity

SELECT u.registered_city, COUNT(*) AS total_sessions
FROM charging_sessions s
JOIN users u ON s.user_id = u.user_id
GROUP BY u.registered_city
ORDER BY total_sessions DESC;

---                                                                     END